name: CI

on:
  push:
    branches-ignore:
      - 'release-*'
    tags-ignore:
      - '*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Create Kubernetes cluster
      id: kind
      uses: engineerd/setup-kind@v0.4.0
      with:
        config: hack/kubernetes/kind.yaml

    - name: e2e-direct
      env:
        GO111MODULE: on
        REGISTRY: appscodeci
        REGISTRY_SECRET: regcred
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        env > ${GITHUB_WORKSPACE}/hack/config/.env
        export GOBIN=$(go env GOPATH)/bin
        mkdir -p $GOBIN
        go env
        export PATH="$GOBIN:$PATH"
        echo $PATH
        go get -u github.com/onsi/ginkgo/ginkgo@v1.10.1
        which ginkgo
        make e2e-direct

    - name: e2e-docker
      env:
        GO111MODULE: on
        REGISTRY: appscodeci
        REGISTRY_SECRET: regcred
        TEST_CREDENTIALS: ${{ secrets.TEST_CREDENTIALS }}
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        $TEST_CREDENTIALS > ${GITHUB_WORKSPACE}/hack/config/.env
        make e2e-tests
