name: Release

on:
  create:
    tags:
      - v*.*.*

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Prepare
      id: prepare
      run: |
        env | grep GITHUB
        TAG=${GITHUB_REF#refs/tags/}
        MINOR=${TAG%.*}
        MAJOR=${MINOR%.*}
        echo ::set-output name=tag_name::${TAG}
        echo ::set-output name=minor_tag::${MINOR}
        echo ::set-output name=major_tag::${MAJOR}
        echo ::set-output name=major_exists::$(git show-ref origin/releases/${MAJOR})

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@master
      with:
        version: latest

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Build
      env:
        REGISTRY: appscodeci
        DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        USERNAME: 1gtm
        APPSCODE_ENV: prod
      run: |
        docker login --username ${USERNAME} --password ${DOCKER_TOKEN}
        make version release
